-- MySQL Script generated by MySQL Workbench
-- Sat Aug 26 18:12:15 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema knela
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `knela` ;

-- -----------------------------------------------------
-- Schema knela
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `knela` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `knela` ;

-- -----------------------------------------------------
-- Table `knela`.`mesas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `knela`.`mesas` (
  `mesa_id` INT NOT NULL AUTO_INCREMENT,
  `capacidad` INT NOT NULL,
  `estado` VARCHAR(20) NOT NULL,
  `mesa_id2` CHAR(36) NULL DEFAULT NULL,
  PRIMARY KEY (`mesa_id`))
ENGINE = InnoDB

DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `knela`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `knela`.`categorias` (
  `categoria_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`categoria_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `knela`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `knela`.`productos` (
  `producto_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `precio_unitario` DECIMAL(10,2) NOT NULL,
  `cantidad_disponible` INT NOT NULL,
  `categoria_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`producto_id`),
  INDEX `categoria_id` (`categoria_id` ASC) VISIBLE,
  CONSTRAINT `productos_ibfk_1`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `knela`.`categorias` (`categoria_id`))
ENGINE = InnoDB

DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `knela`.`carrito_compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `knela`.`carrito_compras` (
  `carrito_id` INT NOT NULL AUTO_INCREMENT,
  `mesa_id` INT NULL DEFAULT NULL,
  `producto_id` INT NULL DEFAULT NULL,
  `cantidad` INT NULL DEFAULT NULL,
  `precio_venta` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`carrito_id`),
  INDEX `mesa_id` (`mesa_id` ASC) VISIBLE,
  INDEX `producto_id` (`producto_id` ASC) VISIBLE,
  CONSTRAINT `carrito_compras_ibfk_1`
    FOREIGN KEY (`mesa_id`)
    REFERENCES `knela`.`mesas` (`mesa_id`),
  CONSTRAINT `carrito_compras_ibfk_2`
    FOREIGN KEY (`producto_id`)
    REFERENCES `knela`.`productos` (`producto_id`))
ENGINE = InnoDB

DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `knela`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `knela`.`clientes` (
  `cliente_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`cliente_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `knela`.`medios_de_pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `knela`.`medios_de_pago` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `knela`.`ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `knela`.`ventas` (
  `venta_id` INT NOT NULL AUTO_INCREMENT,
  `cliente_id` INT NULL DEFAULT NULL,
  `fecha_hora` DATETIME NULL DEFAULT NULL,
  `total` DECIMAL(10,2) NULL DEFAULT NULL,
  `medio_pago_id` INT NULL DEFAULT NULL,
  `cantidad_pago` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`venta_id`),
  INDEX `cliente_id` (`cliente_id` ASC) VISIBLE,
  INDEX `medio_pago_id` (`medio_pago_id` ASC) VISIBLE,
  CONSTRAINT `ventas_ibfk_1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `knela`.`clientes` (`cliente_id`),
  CONSTRAINT `ventas_ibfk_2`
    FOREIGN KEY (`medio_pago_id`)
    REFERENCES `knela`.`medios_de_pago` (`id`))
ENGINE = InnoDB

DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `knela`.`detalles_venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `knela`.`detalles_venta` (
  `detalle_id` INT NOT NULL AUTO_INCREMENT,
  `venta_id` INT NULL DEFAULT NULL,
  `producto_id` INT NULL DEFAULT NULL,
  `cantidad` INT NULL DEFAULT NULL,
  `valor_total` DECIMAL(10,2) NULL DEFAULT NULL,
  `precio_venta` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`detalle_id`),
  INDEX `venta_id` (`venta_id` ASC) VISIBLE,
  INDEX `producto_id` (`producto_id` ASC) VISIBLE,
  CONSTRAINT `detalles_venta_ibfk_1`
    FOREIGN KEY (`venta_id`)
    REFERENCES `knela`.`ventas` (`venta_id`),
  CONSTRAINT `detalles_venta_ibfk_2`
    FOREIGN KEY (`producto_id`)
    REFERENCES `knela`.`productos` (`producto_id`))
ENGINE = InnoDB

DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `knela`.`reservas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `knela`.`reservas` (
  `reserva_id` INT NOT NULL AUTO_INCREMENT,
  `cliente_id` INT NULL DEFAULT NULL,
  `mesa_id` INT NULL DEFAULT NULL,
  `fecha_hora_inicio` DATETIME NULL DEFAULT NULL,
  `fecha_hora_fin` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`reserva_id`),
  INDEX `cliente_id` (`cliente_id` ASC) VISIBLE,
  INDEX `mesa_id` (`mesa_id` ASC) VISIBLE,
  CONSTRAINT `reservas_ibfk_1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `knela`.`clientes` (`cliente_id`),
  CONSTRAINT `reservas_ibfk_2`
    FOREIGN KEY (`mesa_id`)
    REFERENCES `knela`.`mesas` (`mesa_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
