-- MySQL Script generated by MySQL Workbench
-- Sun Aug 20 18:45:31 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema knela2
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `knela2` ;

-- -----------------------------------------------------
-- Schema knela2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `knela2` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `knela2` ;

-- -----------------------------------------------------
-- Table `knela2`.`mesas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `knela2`.`mesas` (
  `mesa_id` INT NOT NULL AUTO_INCREMENT,
  `capacidad` INT NOT NULL,
  `estado` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`mesa_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `knela2`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `knela2`.`categorias` (
  `categoria_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`categoria_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `knela2`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `knela2`.`productos` (
  `producto_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `precio_unitario` DECIMAL(10,2) NOT NULL,
  `cantidad_disponible` INT NOT NULL,
  `categoria_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`producto_id`),
  CONSTRAINT `productos_ibfk_1`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `knela2`.`categorias` (`categoria_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `categoria_id` ON `knela2`.`productos` (`categoria_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `knela2`.`carrito_compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `knela2`.`carrito_compras` (
  `carrito_id` INT NOT NULL AUTO_INCREMENT,
  `mesa_id` INT NULL DEFAULT NULL,
  `producto_id` INT NULL DEFAULT NULL,
  `cantidad` INT NULL DEFAULT NULL,
  `precio_venta` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`carrito_id`),
  CONSTRAINT `carrito_compras_ibfk_1`
    FOREIGN KEY (`mesa_id`)
    REFERENCES `knela2`.`mesas` (`mesa_id`),
  CONSTRAINT `carrito_compras_ibfk_2`
    FOREIGN KEY (`producto_id`)
    REFERENCES `knela2`.`productos` (`producto_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `mesa_id` ON `knela2`.`carrito_compras` (`mesa_id` ASC) VISIBLE;

CREATE INDEX `producto_id` ON `knela2`.`carrito_compras` (`producto_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `knela2`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `knela2`.`clientes` (
  `cliente_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`cliente_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `knela2`.`ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `knela2`.`ventas` (
  `venta_id` INT NOT NULL AUTO_INCREMENT,
  `cliente_id` INT NULL DEFAULT NULL,
  `fecha_hora` DATETIME NULL DEFAULT NULL,
  `total` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`venta_id`),
  CONSTRAINT `ventas_ibfk_1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `knela2`.`clientes` (`cliente_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `cliente_id` ON `knela2`.`ventas` (`cliente_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `knela2`.`detalles_venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `knela2`.`detalles_venta` (
  `detalle_id` INT NOT NULL AUTO_INCREMENT,
  `venta_id` INT NULL DEFAULT NULL,
  `producto_id` INT NULL DEFAULT NULL,
  `cantidad` INT NULL DEFAULT NULL,
  `valor_total` DECIMAL(10,2) NULL DEFAULT NULL,
  `precio_venta` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`detalle_id`),
  CONSTRAINT `detalles_venta_ibfk_1`
    FOREIGN KEY (`venta_id`)
    REFERENCES `knela2`.`ventas` (`venta_id`),
  CONSTRAINT `detalles_venta_ibfk_2`
    FOREIGN KEY (`producto_id`)
    REFERENCES `knela2`.`productos` (`producto_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `venta_id` ON `knela2`.`detalles_venta` (`venta_id` ASC) VISIBLE;

CREATE INDEX `producto_id` ON `knela2`.`detalles_venta` (`producto_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `knela2`.`reservas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `knela2`.`reservas` (
  `reserva_id` INT NOT NULL AUTO_INCREMENT,
  `cliente_id` INT NULL DEFAULT NULL,
  `mesa_id` INT NULL DEFAULT NULL,
  `fecha_hora_inicio` DATETIME NULL DEFAULT NULL,
  `fecha_hora_fin` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`reserva_id`),
  CONSTRAINT `reservas_ibfk_1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `knela2`.`clientes` (`cliente_id`),
  CONSTRAINT `reservas_ibfk_2`
    FOREIGN KEY (`mesa_id`)
    REFERENCES `knela2`.`mesas` (`mesa_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `cliente_id` ON `knela2`.`reservas` (`cliente_id` ASC) VISIBLE;

CREATE INDEX `mesa_id` ON `knela2`.`reservas` (`mesa_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
