-- MySQL Script generated by MySQL Workbench
-- Wed Jul 19 16:45:34 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sales
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sales` ;

-- -----------------------------------------------------
-- Schema sales
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sales` DEFAULT CHARACTER SET utf8 ;
USE `sales` ;

-- -----------------------------------------------------
-- Table `sales`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sales`.`categorias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sales`.`proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sales`.`proveedores` (
  `rut` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`rut`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sales`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sales`.`productos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `precio` DECIMAL(10,2) NOT NULL,
  `stok` INT NULL,
  `categorias_id` INT NOT NULL,
  `proveedores_rut` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_productos_categorias`
    FOREIGN KEY (`categorias_id`)
    REFERENCES `sales`.`categorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_productos_proveedores1`
    FOREIGN KEY (`proveedores_rut`)
    REFERENCES `sales`.`proveedores` (`rut`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_productos_categorias_idx` ON `sales`.`productos` (`categorias_id` ASC) VISIBLE;

CREATE INDEX `fk_productos_proveedores1_idx` ON `sales`.`productos` (`proveedores_rut` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `sales`.`cientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sales`.`cientes` (
  `rut` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NULL,
  PRIMARY KEY (`rut`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sales`.`ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sales`.`ventas` (
  `ip` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `cientes_rut` INT NOT NULL,
  PRIMARY KEY (`ip`),
  CONSTRAINT `fk_ventas_cientes1`
    FOREIGN KEY (`cientes_rut`)
    REFERENCES `sales`.`cientes` (`rut`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_ventas_cientes1_idx` ON `sales`.`ventas` (`cientes_rut` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `sales`.`detalle_venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sales`.`detalle_venta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `precio` DECIMAL(10,2) NOT NULL,
  `cantidad` INT NOT NULL,
  `productos_id` INT NOT NULL,
  `ventas_ip` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_detalle_venta_productos1`
    FOREIGN KEY (`productos_id`)
    REFERENCES `sales`.`productos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_venta_ventas1`
    FOREIGN KEY (`ventas_ip`)
    REFERENCES `sales`.`ventas` (`ip`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_detalle_venta_productos1_idx` ON `sales`.`detalle_venta` (`productos_id` ASC) VISIBLE;

CREATE INDEX `fk_detalle_venta_ventas1_idx` ON `sales`.`detalle_venta` (`ventas_ip` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `sales`.`compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sales`.`compras` (
  `ip` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `proveedores_rut` INT NOT NULL,
  PRIMARY KEY (`ip`),
  CONSTRAINT `fk_compras_proveedores1`
    FOREIGN KEY (`proveedores_rut`)
    REFERENCES `sales`.`proveedores` (`rut`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_compras_proveedores1_idx` ON `sales`.`compras` (`proveedores_rut` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `sales`.`detalle_compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sales`.`detalle_compra` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `precio` DECIMAL(10,2) NOT NULL,
  `cantidad` INT NOT NULL,
  `compras_ip` INT NOT NULL,
  `productos_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_detalle_compra_compras1`
    FOREIGN KEY (`compras_ip`)
    REFERENCES `sales`.`compras` (`ip`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_compra_productos1`
    FOREIGN KEY (`productos_id`)
    REFERENCES `sales`.`productos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_detalle_compra_compras1_idx` ON `sales`.`detalle_compra` (`compras_ip` ASC) VISIBLE;

CREATE INDEX `fk_detalle_compra_productos1_idx` ON `sales`.`detalle_compra` (`productos_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
